string group_name
string[] joint_names
uint32 dof
float64[] start
float64[] goal
float64[] intent_flat
uint32 intent_points
float64 t_start
float64 t_end
float64[] state_min
float64[] state_max
float64 timeout_sec
uint32 max_iter
float64 step_size
float64 goal_tolerance
float64 edge_resolution
float64 p_intent
float64 p_goal
float64 p_uniform
float64 sigma_intent
uint32 rng_seed
---
bool ok
float64[] path_flat
uint32 path_points
float64[] via_times
string stop_reason
string error_message
float64 elapsed_ms
uint32 iter_used
uint32 collision_queries
