workspace_root: "../../workspaces/multibot_ws"

ur_move:
  host: "127.0.0.1"
  port: 5605
  timeout_sec: 60.0
  planner: "lin"
  velocity_scale: 0.1
  acceleration_scale: 0.1

group_name: "left_arm"
ik_frame: "left_ee_link"

plane:
  frame_id: "left_interface_link"
  algorithm_coordinate_mode: "normalized"
  x_min: 0.50
  x_max: 0.68
  y_min: 0.06
  y_max: 0.24
  z: 0.35

orientation_xyzw: [0.3826834323650898, 0.0, 0.0, 0.9238795325112867]

obstacle_input:
  coordinate_mode: "normalized"
  frame_id: "left_interface_link"
  radius_scale_mode: "min"

drawing_plane:
  table_surface_z: -0.0102

drawing:
  enabled: true
  task_frame: "left_interface_link"
  tool_tip_link: "left_pen_tip_link"
  table_surface_z: -0.0102
  contact_clearance: 0.002
  drawing_tip_z: "auto"
  orientation_xyzw: [0.3826834323650898, 0.0, 0.0, 0.9238795325112867]

tool:
  parent_link: "left_ee_link"
  tip_link: "left_pen_tip_link"
  ee_to_tip:
    translation: [0.0, -0.10606601717798213, -0.10606601717798213]
    rotation_xyzw: [-0.3826834323650898, 0.0, 0.0, 0.9238795325112867]

scene_obstacles:
  sync_to_moveit: true
  frame_id: "left_interface_link"
  cylinder_height: 0.18
  center_z_mode: "from_table_surface"
  table_surface_z: -0.0102
  radius_scale_mode: "min"
  publish_repeats: 3
  clear_slots: 8
  id_prefix: "plane_demo_left"

waypoints:
  resample_count: 30
  simplify_min_dist: 0.0
  clamp_uv: true

execution:
  plan_only: true
  execute: false
  move_to_start_first: true
  preposition_planner: "ompl"
